[project]
name = "slowrun"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.6.0",
    "numpy>=2.4.2",
    "tiktoken>=0.12.0",
    "torch>=2.10.0",
    "wandb>=0.25.0",
]
